#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

yarn version --patch --no-git-tag-version   # Bump patch version in package.json
  git add package.json                       # Stage the updated package.json
  git commit -m "Bump version"               # Commit the version change
